<?php

/**
 * @file
 * Contains tcm_api.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function tcm_api_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the tcm_api module.
    case 'help.page.tcm_api':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Awesome Movies') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function tcm_api_theme($existing, $type, $theme, $path) {
  return [
    'movie' => [
      'variables' => [
          'id' => '',
          'title' => '',
          'description' => '',
          'image' => '',
          'year' => '',
      ],
    ],
    'movies' => [
      'variables' => [
        'movies' => ''
      ]
    ],
    'movie_search_form' => [
      'render element' => 'form'
  ];
}